package com.example.venueSelector

const val IMAGE_BASE_URL = "https://cdn.kadalpura.com/calendar/coffee-meet/"
const val CONTENT_DESCRIPTION_BASE = "Venue Image at "
const val REGISTER = "Register"
const val REGISTERING = "Registering"
const val UNREGISTERING = "Unregistering"
const val LOADING = "Loading"
const val DIALOG_TITLE = "People Registered"
const val NONE_REGISTERED = "No one has registered yet!"
const val OPEN_MAPS = "Open Google Maps"
const val OPENING_MAPS = "Opening Maps"
const val AVAILABLE_VENUES = "Available Venues"
const val NAME_INPUT = "Your Name"
const val NAME_REQ = "\nName is required"
const val LOCATION_INPUT = "Your Current Location"
const val LOCATION_REQ = "\nLocation is required"
const val PHONE_NUMBER_REQ1 = "\nEnter a valid phone number (With country code)"
const val PHONE_NUMBER_REQ2 = "Phone Number Already Used"
const val PHONE_NUMBER_REQ3 = "Phone Number Already Entered Elsewhere"
const val PHONE_NUMBER_INPUT = "Your Phone Number"
val PHONE_NUMBER_REGEX = Regex("""^\+?[1-9]\d{10,14}$""")
const val FINISH_REGISTERING = "Finish Registering"
const val REGISTER_SUCCESSFUL = "Successfully Registered!"
const val BACK_TO_AVAILABLE_VENUES = "Back to Available Venues"
